wfischer42/little_shop

- Gemfile
- Gemfile.lock
- app/models/user.rb
- db/migrate/20181023145241_create_users.rb
- db/schema.rb
- spec/factories/users.rb
- spec/models/user_spec.rb
> Added user model

- app/models/item.rb
- spec/factories/items.rb
- spec/models/item_spec.rb
> Added Item Model

- app/assets/stylesheets/application.css
- db/schema.rb
Fixes application.css file (adds info back in i removed last night)
Fixes schema, role to user.  
closes #
> fixes application css file and schema role for user

- app/models/item.rb
- spec/factories/items.rb
- spec/models/item_spec.rb
* Modified relation between Items with User, using an the alias of merchant
* added functionality to Items factory bot to create many Items related to merchants
closes #85
> Alias mechant items#85

- spec/features/visitor_can_use_nav_spec.rb
Updated nav bar test to shoulda matchers
closes #
> changes nav bar test to use should matchers

- app/controllers/items_controller.rb
- app/controllers/merchants_controller.rb
- app/models/merchant.rb
- app/views/items/index.html.erb
- app/views/items/show.html.erb
- app/views/merchants/index.html.erb
- app/views/users/index.html.erb
- spec/features/user_can_view_all_merchants_spec.rb
- [ x] Wrote Tests
Wrote 1 test - want to merge before pulling down branch with factory bots to create more dynamic tests
- [x ] All Tests are Passing
Implemented basic HTML to show pages for user, merchant, item.
- [x ] This broke nothing
- [ x] No Tests have been changed
- [x ] I have reviewed my code
> basic HTML layout created for index views of merchant, item, and user

- app/controllers/sessions_controller.rb
- app/controllers/users_controller.rb
- app/views/layouts/application.html.erb
- app/views/sessions/new.html.erb
- app/views/users/new.html.erb
- config/routes.rb
- spec/features/visitor_can_use_nav_spec.rb
Adds login and register links to nav bar
adds session controller for login
adds user controller for register page
closes #16
> adds login and register links to nav bar

- app/models/order.rb
- db/migrate/20181023155416_create_orders.rb
- db/schema.rb
- spec/factories/items.rb
- spec/factories/order_items.rb
- spec/factories/orders.rb
- spec/models/order_spec.rb
* added enum functionality to Order model
* added relationship to factory bot
closes #
> Configure factories#89

- app/controllers/application_controller.rb
- app/controllers/users_controller.rb
- app/views/users/profile.html.erb
- config/routes.rb
- spec/features/user_go_to_profile_page_spec.rb
* Added User profile page.
* missing functionality for the link to User order, because the functionality is not built yet.
* Two test skiped
closes #
> Profile page#27

- db/seeds.rb
Created a seed file that adds Faker data for customers, merchants, admins, items, orders (and order_items). 
Accounts for an Admin, a Customer, and a Merchant have been set up to allow access. This will need to be checked once we have our authentication system in place.
```
email: merchant@merchant.com
pass: merchant
```
```
email: customer@customer.com
pass: customer
```
```
email: admin@admin.com
pass: admin
```
closes #88
> Added seed file. Will need validation after logins are implemented

- app/controllers/application_controller.rb
- app/controllers/users_controller.rb
- app/views/users/new.html.erb
- config/routes.rb
- spec/features/visitor_can_register_spec.rb
- spec/features/visitor_can_use_nav_spec.rb
Adds user create form. 
Tests that form creates user properly
Tests edge cases for incorrect password
Tests edge cases for missing field
> User create#24

- app/controllers/sessions_controller.rb
- app/controllers/users_controller.rb
- app/views/sessions/new.html.erb
- config/routes.rb
- spec/features/User_can_view_all_merchants_spec.rb
- spec/features/user_can_log_in_spec.rb
Added login functionality that successfully authenticates correct credentials, or rejects invalid credentials. Session storage and "current_user" behave as expected.
closes #51
> Added login functionality

- app/controllers/admin/merchants_controller.rb
- app/controllers/application_controller.rb
- app/controllers/merchants_controller.rb
- app/views/merchants/index.html.erb
- app/views/users/index.html.erb
- config/routes.rb
- db/seeds.rb
- spec/features/Admin_or_visitor_views_all_merchants_spec.rb
- spec/features/Merchant_or_registered_user_views_all_merchants_spec.rb
- spec/features/admin_can_enable_and_disables_merchant_spec.rb
Updated admin routes to use scope instead of namespace. The '/merchants' path no longer has an admin/ version. Instead, it conditionally displays admin functions. Also updated the Seed file to fix the log-innable accounts. Now the username and password are both "admin" for admins, "merchant" for merchants, and "customer" for customer. Tests have been updated to reflect changes.
> Little fixes#107

- app/assets/stylesheets/application.css
- app/controllers/items_controller.rb
- app/views/items/index.html.erb
- app/views/items/show.html.erb
- config/routes.rb
- spec/features/visitor_can_see_item_show_spec.rb
Adds Item show page with testing.
Adds links from item index to show page. 
closes #46
> adds item show page with styling

- app/controllers/application_controller.rb
- app/controllers/cart_items_controller.rb
- app/models/cart_item.rb
- app/models/concerns/cart.rb
- app/views/cart_items/index.html.erb
- app/views/items/show.html.erb
- config/routes.rb
- spec/features/visitor_can_add_items_to_cart_spec.rb
Adds button on item show to add item to cart
Adds basic information about the items to the cart
closes #111
> adds button to item show page to add items to cart

- spec/features/admin_can_enable_and_disables_merchant_spec.rb
- [ x] Wrote Tests
- [ x] Implemented
- [ x] Reviewed
- [ x] All Tests are Passing
- [ x] The code will run locally
- [ x] New feature
closes #59 
closes #57 
- [x ] This broke nothing
- [ x] No Tests have been changed
- [x ] My code has no unused/commented out code
- [ x] I have reviewed my code
- [ x] I have fully tested my code
> initial commit, first test passing

- app/assets/stylesheets/application.css
- app/controllers/orders_controller.rb
- app/controllers/sessions_controller.rb
- app/views/users/profile.html.erb
- config/routes.rb
- spec/features/user_can_go_to_profile_page_spec.rb
I started out with the goal of making our two skipped tests pass, which were testing a link to an orders page from the profile page. But to do that I had to add the route and controller. So I added the `profile/orders`, `dashboard/orders`, and `/users/:id/orders` (admin only) routes, and set up a controller and an empty order index page. It will need to be updated to display conditionally, and tests will need to reflect that. 
Also took care of some minor spelling & format 'errors' here and there.
closes #118
> Added orders index route & controller

- README.md
- app/controllers/application_controller.rb
- app/controllers/users_controller.rb
- app/views/users/edit.html.erb
- config/routes.rb
- spec/features/user_can_update_it_own_profile_spec.rb
Routes should be pretty much good to go. Name-spaced routes (particularly "admin" and "merchant" namespaces) exist to apply filters to make sure only admins or merchants can see them. If these checks fail, I'm pretty sure a 404 should be rendered in most cases. Otherwise, they will often only be responsible for finding out which DB entries should be passed to the views, and the views should render partials based on the results.
For update/disable/enable/upgrade/downgrade type things, the controller should determine which entries to apply the action to, then send it into a helper method that calls the model methods and/or ActiveRecord actions.
I rebased before pulling, but it will likely cause some issues in whatever branches you're working on.
closes #121
> Updated routes

- app/controllers/cart_items_controller.rb
- app/models/cart_item.rb
- app/models/concerns/cart.rb
- app/views/cart_items/index.html.erb
- config/routes.rb
- spec/features/visitor_can_add_items_to_cart_spec.rb
Adds cart. 
Adds information to cart items such as quantity and subtotal
adds grand total
adds empty cart link. 
closes #43
> adds cart show page with totals, sub totals

- app/controllers/admin/merchants_controller.rb
- app/controllers/admin/users_controller.rb
- app/controllers/users_controller.rb
- app/views/users/_user_profile.html.erb
There was a bug when the admin visited `/profile` which caused 2 tests to fail. It's been fixed.
> Fixed bug from profile partial when admin visits own profile page

- spec/features/any_usr_can_increase_cart_item_spec.rb
Adds limit to cart item increase to not go above the inventory count that the merchant has on hand. 
closes #
> fixes test for increase item on cart

- app/views/cart_items/index.html.erb
- spec/features/any_user_can_interact_with_cart_spec.rb
Adds checkout button for user, merchant and admin.  
Button does not show up for visitor
Button does not show up if the grand total is less than $0.01. 
closes #19
> adds checkout button for user if there are items in the cart

- app/assets/stylesheets/application.css
- app/controllers/application_controller.rb
- app/views/layouts/_nav.html.erb
- spec/features/visitor_can_use_nav_spec.rb
Set up nav bar links for merchants and updated link spacing css to accomodate extra links
closes #22
> Added custom nav links for merchants.

- app/assets/stylesheets/application.css
- app/views/layouts/_nav.html.erb
- spec/features/visitor_can_use_nav_spec.rb
Added admin nav links & name label for logged in admin.
closes #23
> Admin nav#23

- app/views/cart_items/index.html.erb
- spec/features/any_user_can_interact_with_cart_spec.rb
Adds logic for visitor to login/register in order to complete their order
Adds logic that the cart total has to be over .01 for links to show up to checkout/login/register
closes #20
> shows links to register or login if user isnt logged in

- db/seeds.rb
The title says it all.
closes #120
> Updated img url seed so images are random

- app/controllers/users_controller.rb
- spec/features/visitor_can_register_spec.rb
Changes wording on flash message for the first time you register. 
closes #
> fixes wording on flash message for visitor logging in

- app/controllers/sessions_controller.rb
- spec/features/logged_user_visit_log_path_and_get_redirected_to_show_page_spec.rb
* Added functionality  when logged users  try to go to login path, system redirect them to profile page and display a message User is logged in
closes #52
> story 17 complete, with test

- app/assets/stylesheets/application.css
- app/controllers/sessions_controller.rb
- app/views/layouts/_nav.html.erb
- spec/features/user_can_log_in_spec.rb
- spec/features/visitor_can_use_nav_spec.rb
Added login flash message and 'Logged in as...' tag to nav bar
closes #137 
closes #51
> Added flash messages & login labels

- app/controllers/items_controller.rb
- spec/factories/items.rb
- spec/features/user_visit_item_index_spec.rb
> fixed bug in item index page that was displaying inactive items

- app/controllers/sessions_controller.rb
- spec/features/user_can_log_in_spec.rb
Disabled users and merchants can no longer log in, and when they're re-enabled, they can log in again.
closes #58 
closes #139 
closes #60
> Disabled users and merchants can't log in.

- app/controllers/admin/merchants_controller.rb
- app/controllers/admin/users_controller.rb
- spec/features/admin_can_edit_merchant_profile_data_spec.rb
- spec/features/admin_can_edit_user_profile_data_spec.rb
- [ x] Wrote Tests
- [ x] Implemented
- [ x] Reviewed
- [x ] All Tests are Passing
- [ x] The code will run locally
- [x ] New feature
- [x ] Bug Fix
Fixes routing errors in admin/merchants#show controller.
Fixes routing errors in admin/merchants and admin/users controller - when a user is upgraded or downgraded, the path changes from merchants/id to users/id respectively.
Adds admin functionality for viewing the users index page and a user profile page, including updating user data.
NOTE: a separate issue card has been created to address disabled users being unable to log in, which is part of the current issue.
closes #
- [ x] This broke nothing
- [ x] No Tests have been changed
- [ x] I have reviewed my code
- [ x] I have fully tested my code
> Admin user page functions #41 #42 #64

- app/controllers/merchant/base_controller.rb
- app/controllers/merchant/items_controller.rb
- app/views/users/_dashboard.html.erb
- app/views/users/dashboard.html.erb
- spec/features/merchant_dashboard_spec.rb
Adds partial for dashboard for future use with admin
Adds Merchant base controller
Adds MerchantItems controller
Adds link from merchant dashboard to merchant items
closes #32
> adds controller for merchant items

- app/controllers/cart_items_controller.rb
- app/controllers/orders_controller.rb
- app/models/order.rb
- app/views/cart_items/index.html.erb
- config/routes.rb
- spec/features/user_checkout_and_order_management_spec.rb
- spec/models/order_spec.rb
Cart checkout button creates an order entry with the items and their cart quantity in the order_items join table, then redirects to the profile/orders page for the purchasing user.
closes #18
> Added cart checkout functionality.

- app/controllers/users_controller.rb
Updates user register to fail if email is already in system
closes #
> updates register to fail if email supplied is already in use

- app/controllers/orders_controller.rb
- spec/features/any_user_can_interact_with_cart_spec.rb
- spec/features/user_checkout_and_order_management_spec.rb
Added test to make sure cart clears when checking out.
closes #18 (again)
> Added test for cart reset at checkout.

- app/views/layouts/_nav.html.erb
- spec/features/visitor_can_use_nav_spec.rb
The title says it all
closes #23
> Added users link to admin nav

- app/controllers/cart_items_controller.rb
- app/models/concerns/cart.rb
- spec/models/cart_spec.rb
Adds testing for cart model
closes #
> Cart model test

- app/controllers/items_controller.rb
- app/controllers/orders_controller.rb
- app/models/order.rb
- app/models/user.rb
- app/views/orders/index.html.erb
- spec/features/user_checkout_and_order_management_spec.rb
- spec/models/order_spec.rb
- spec/models/user_spec.rb
Added 'user has many items' and 'user has many orders' relationships. Created order model method for calculating grand total using ActiveRecord. Grand total is displayed on order show-page for current user.
> Order show#17

- app/assets/stylesheets/application.css
- app/models/item.rb
- app/models/user.rb
- app/views/partial/_card.html.erb
- spec/features/all_users_see_item_index_stats_spec.rb
- spec/features/user_visit_item_index_spec.rb
- [ x] Wrote Tests
- [ x] Implemented
- [ x] Reviewed
- [ x] All Tests are Passing
- [ x] The code will run locally
- [ x] New feature
Restyles item index page using _card partial, and edits existing css.
- [x ] This broke nothing
- [ x] Some Tests have been changed -- Had to change the CSS tag in one existing test
- [ x] My code has no unused/commented out code
- [x ] I have reviewed my code
- [ x] I have commented my code, particularly in hard-to-understand areas
- [ x] I have fully tested my code
> Item index styling

- app/controllers/merchant/items_controller.rb
- app/views/merchant/items/index.html.erb
- app/views/partial/_card.html.erb
- spec/features/merchants/merchant_can_see_merchant_items_index_spec.rb
closes #35
closes #33
closes #34
> Merchant items index#33

- app/views/merchant/items/index.html.erb
- config/routes.rb
- spec/features/merchants/merchant_can_see_merchant_items_index_spec.rb
Adds link to merchant item index page. 
closes #
> adds new button to merchant item index

- Gemfile.lock
- app/controllers/merchant/items_controller.rb
- app/views/merchant/items/new.html.erb
- spec/features/merchants/merchant_can_add_item_spec.rb
> adds new item for merchant with tests for edge cases

- .gitignore
- app/controllers/admin/orders_controller.rb
- app/views/admin/orders/index.html.erb
- app/views/orders/_order_info.html.erb
- spec/features/orders/admin_order_management_spec.rb
- spec/features/orders/user_checkout_and_order_management_spec.rb
Admin can view /orders path and cancel orders.
closes #9
> Added ability for admin to cancel orders

- app/controllers/merchant/orders_controller.rb
- app/controllers/users_controller.rb
- app/models/user.rb
- app/views/users/_dashboard.html.erb
- spec/features/merchants/merchant_dashboard_see_orders_link_spec.rb
- spec/features/merchants/merchant_dashboard_spec.rb
- spec/models/user_spec.rb
* Added feature were Merchant user without Customer orders can't see link to My Orders in their dashboard
closes #55
> Merchant dashboard#20

- spec/features/login-out/visitor_can_register_spec.rb
Fixed test to check to see if a new user reg will fail if they try to use an email that is in the database already.  Test was written but wasn't checking to see if the flash message showed up.  
closes #
> fixes test to check to see if email exists when creating a new user

- app/assets/stylesheets/application.css
- app/views/merchant/items/new.html.erb
> fixes css for min width on items partial for the image

- app/models/user.rb
Fixes bug on user model. 
closes #
> merchant orders bug fix

- app/views/cart_items/index.html.erb
- spec/features/cart/any_user_can_interact_with_cart_spec.rb
Adds link to items on the cart page if the cart is empty.
Fixes test to test for above conditions.  
closes #
> adds empty cart with link to items if no items are in the cart

- app/controllers/users_controller.rb
- spec/features/users/user_can_update_it_own_profile_spec.rb
Fixed user update tests and applied current_user helper method to user controller methods.
closes #
> Updated users controller method to use 'current_user'. Fixed tests

- app/controllers/merchant/items_controller.rb
- app/views/merchant/items/_form.html.erb
- app/views/merchant/items/edit.html.erb
- app/views/merchant/items/new.html.erb
- spec/features/merchants/merchant_can_edit_item_spec.rb
closes #38
closes #39
closes #40
> Merchant edit#38

- spec/features/users/user_can_update_it_own_profile_spec.rb
So, it turns out the fix wasn't finished when I pulled. It's all passing now, and the commented code is removed.
closes #
> Finished the fix

- app/controllers/merchant/items_controller.rb
- app/views/admin/orders/index.html.erb
- app/views/merchant/items/_form.html.erb
- app/views/orders/index.html.erb
- app/views/users/_dashboard.html.erb
- app/views/users/_user_profile.html.erb
- spec/features/merchants/merchant_dashboard_see_orders_link_spec.rb
- spec/features/users/user_can_go_to_profile_page_spec.rb
Adds link to admin dashboard to view all items
Adds headers to view pages to be more clear about which page you are on. 
closes #
> Page titles

- app/controllers/admin/orders_controller.rb
- spec/features/cart/any_user_can_interact_with_cart_spec.rb
Fixes bug in test num_to_currency
closes #
> fixes test

- app/controllers/admin/orders_controller.rb
- app/controllers/merchant/orders_controller.rb
- app/views/admin/merchants/show.html.erb
- app/views/admin/users/show.html.erb
- config/environments/test.rb
- spec/features/admin/admin_can_manage_orders_spec.rb
- spec/features/orders/admin_order_management_spec.rb
> Admin merchant orders#63

- app/controllers/admin/orders_controller.rb
- spec/features/admin/admin_can_manage_orders_spec.rb
> Fixed bug from dual merge

- spec/features/cart/any_user_can_interact_with_cart_spec.rb
Fixes number_to_currency in test file for cart
closes #
> fixes cart test for num to currency

- app/controllers/users_controller.rb
- app/models/order.rb
- app/models/order_item.rb
- app/models/user.rb
- app/views/users/_dashboard.html.erb
- db/seeds.rb
- spec/features/admin/admin_can_enable_and_disable_items_spec.rb
- spec/features/admin/admin_views_admin_dashboard_spec.rb
- spec/models/order_item_spec.rb
- spec/models/order_spec.rb
- spec/models/user_spec.rb
- [x ] Wrote Tests
- [x ] Implemented
- [x ] Reviewed
- [x ] All Tests are Passing
- [x ] The code will run locally
- [ x] New feature
adds stats to admin dashboard
closes #7 
- [x ] This broke nothing
- [x ] No Tests have been changed
- [x ] My code has no unused/commented out code
- [x ] I have reviewed my code
- [x ] I have fully tested my code
> finishes admin dashboard stats

- app/controllers/merchant/order_items_controller.rb
- app/controllers/merchant/orders_controller.rb
- app/models/order_item.rb
- app/views/merchant/orders/show.html.erb
- config/routes.rb
- spec/features/orders/merchant_can_fulfill_item_of_order_spec.rb
- spec/models/order_item_spec.rb
- [] Bug Fix
* Implemented functionality to complete user story 52
closes #12 
- [x ] Some Tests have been changed
> Order show b#12
